namespace Loupedeck.ClaudeConsolePlugin.Actions
{
    using System;
    using System.Threading;

    /// <summary>
    /// Voice key — offline dictation via the bundled ClaudeVoiceHelper.app (whisper.cpp, no cloud).
    ///
    /// Press once to start recording (you'll hear a "Tink"), speak, then press again to stop:
    /// the helper transcribes locally and the plugin types the text into the focused terminal.
    /// While recording, the face animates a green equalizer (cycled wave0..wave3 frames) so the key
    /// visibly "listens", and the title switches to "Listening".
    ///
    /// Recording lives in a separate signed app bundle because it holds its OWN Microphone
    /// permission — LogiPluginService (a background daemon) cannot get mic access directly. The
    /// start/stop plumbing is in BridgeManager.StartVoiceCapture / StopVoiceCapture; the bundle
    /// and its build script are in tools/voice/.
    /// </summary>
    public class VoiceCommand : PluginDynamicCommand
    {
        // Equalizer frames cycled while recording (generated by tools/generate-icons.swift).
        private static readonly String[] WaveFrames = { "wave0", "wave1", "wave2", "wave3" };

        private Boolean _recording;
        private Timer _animTimer;
        private Int32 _frame;

        public VoiceCommand()
            : base(displayName: "Voice", description: "Speak a prompt — press to start, press again to transcribe and send", groupName: "Universal")
        {
        }

        protected override void RunCommand(String actionParameter)
        {
            var bridge = BridgeManager.Instance;
            if (!_recording)
            {
                bridge.StartVoiceCapture();
                StartWaveAnimation();
            }
            else
            {
                bridge.StopVoiceCapture();
                StopWaveAnimation();
            }

            _recording = !_recording;
            this.ActionImageChanged();
            PluginLog.Info($"VoiceCommand: recording={_recording}");
        }

        // Cycle the equalizer ~6x/sec so the Voice key looks "live" while it listens.
        private void StartWaveAnimation()
        {
            _frame = 0;
            _animTimer?.Dispose();
            _animTimer = new Timer(_ =>
            {
                _frame++;
                this.ActionImageChanged();
            }, null, 150, 150);
        }

        private void StopWaveAnimation()
        {
            _animTimer?.Dispose();
            _animTimer = null;
        }

        protected override String GetCommandDisplayName(String actionParameter, PluginImageSize imageSize) =>
            _recording ? "Listening" : "Voice";

        protected override BitmapImage GetCommandImage(String actionParameter, PluginImageSize imageSize) =>
            _recording
                ? KeyImage.Render(imageSize, "Listening", KeyImage.Green, WaveFrames[_frame % WaveFrames.Length])
                : KeyImage.Render(imageSize, "Voice", KeyImage.Purple, "voice");
    }
}
