namespace Loupedeck.ClaudeConsolePlugin
{
    using System;
    using System.Threading;

    /// <summary>
    /// The animated "Listening" face shared by every key that drives the voice recorder (Voice,
    /// Go to Project). Owns the frame timer so each key doesn't re-implement it, and so all of them
    /// animate identically — a key that records should always look like it's recording.
    ///
    /// <c>Icon</c> names a wave frame (generated by tools/generate-icons.swift); its colour is baked
    /// into the PNG, so callers pass any accent to <see cref="KeyImage.Render"/> — it is ignored.
    /// </summary>
    internal sealed class ListeningFace : IDisposable
    {
        private static readonly String[] Frames = { "wave0", "wave1", "wave2", "wave3" };

        // ~6 fps — fast enough to read as "live", slow enough not to churn the key's LCD.
        private const Int32 FrameMs = 150;

        private readonly Action _onFrame;
        private Timer _timer;
        private Int32 _frame;

        public ListeningFace(Action onFrame) => _onFrame = onFrame;

        /// <summary>True while the animation is running, i.e. while this key is recording.</summary>
        public Boolean IsActive => _timer != null;

        /// <summary>Current wave frame's icon basename.</summary>
        public String Icon => Frames[_frame];

        public void Start()
        {
            _frame = 0;
            _timer?.Dispose();
            // Wrap the frame index here rather than at the read site so it can never go negative
            // (an unbounded Int32 counter eventually overflows, and a negative % is negative).
            _timer = new Timer(
                _ =>
                {
                    _frame = (_frame + 1) % Frames.Length;
                    _onFrame();
                },
                null, FrameMs, FrameMs);
        }

        public void Stop()
        {
            _timer?.Dispose();
            _timer = null;
        }

        public void Dispose() => this.Stop();
    }
}
