namespace Loupedeck.ClaudeConsolePlugin
{
    using System;
    using System.Threading;

    /// <summary>
    /// The animated "Listening" face shared by every key that drives the voice recorder (Voice,
    /// Go to Project). Owns the frame timer so each key doesn't re-implement it, and so all of them
    /// animate identically — a key that records should always look like it's recording.
    ///
    /// <c>Icon</c> names a wave frame (generated by tools/generate-icons.swift); its colour is baked
    /// into the PNG, so callers pass any accent to <see cref="KeyImage.Render"/> — it is ignored.
    /// </summary>
    internal sealed class ListeningFace : IDisposable
    {
        private static readonly String[] Frames = { "wave0", "wave1", "wave2", "wave3" };

        // ~6 fps — fast enough to read as "live", slow enough not to churn the key's LCD.
        private const Int32 FrameMs = 150;

        private readonly Action _onFrame;
        private Timer _timer;
        private Int32 _frame;
        private readonly Object _gate = new();
        private Int64 _generation;
        private Int32 _drawing;
        private Boolean _enabled = true;

        public ListeningFace(Action onFrame) => _onFrame = onFrame;

        /// <summary>True while the animation is running, i.e. while this key is recording.</summary>
        public Boolean IsActive => _timer != null;

        /// <summary>Current wave frame's icon basename.</summary>
        public String Icon => Frames[_frame];

        public void Start()
        {
            lock (_gate)
            {
                if (!_enabled) return;
                _frame = 0;
                _timer?.Dispose();
                var generation = ++_generation;
                _timer = new Timer(_ => DrawFrame(generation), null, FrameMs, Timeout.Infinite);
            }
        }

        private void Arm(Int64 generation)
        {
            lock (_gate) if (generation == _generation) _timer?.Change(FrameMs, Timeout.Infinite);
        }

        private void DrawFrame(Int64 generation)
        {
            lock (_gate) if (generation != _generation || _timer == null) return;
            if (Interlocked.Exchange(ref _drawing, 1) != 0) { Arm(generation); return; }
            try
            {
                _frame = (_frame + 1) % Frames.Length;
                _onFrame();
            }
            catch { /* A stopped SDK renderer must not terminate a timer thread. */ }
            finally { Volatile.Write(ref _drawing, 0); Arm(generation); }
        }

        public void Stop()
        {
            lock (_gate)
            {
                _generation++;
                _timer?.Dispose();
                _timer = null;
            }
        }

        internal void SetEnabled(Boolean enabled)
        {
            lock (_gate)
            {
                _enabled = enabled;
                if (!enabled) Stop();
            }
        }

        public void Dispose() => this.Stop();
    }
}
